[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
take-until = "0.1.0"
num = "0.4.0"
pathfinding = "4.0.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
